### ISSUE TITLE
display: Repo has diverged from remote

### ISSUE THREAD

**Issue by DoomerDGR8** [OpenNeptune3D/display_connector#23]
I'm trying to figure out this issue:

![image](https://github.com/user-attachments/assets/026c23fe-72f2-4d69-99d5-e54963ad95c6)

I followed the guide to install OpenNept4une to the letter. I upgraded the touch screen to the latest official firmware already before starting/switching to OpenNept4une.

The screen is working and is showing extra information compared to Elegoo's official firmware but within Fluid's Software update, I have this particular component reporting the error.

**Comment by virajmalia** [comment]
Here's what worked for me:
1. Recover and restart the host.
2. After restart it will throw some warnings and the display will enter a bootloop:
![image](https://github.com/user-attachments/assets/4e8749e0-ba00-4e3e-9ba5-8c95f352c2c8)
3. Using any terminal, `ssh mks@<printer_ip>`. Password is `makerbase`.
4. `cd /home/mks/display_connector && ./install.sh full`. This will reinstall the display connector with the latest version.

**Comment by DoomerDGR8** [comment]
Resolved from above suggestion.
