### ISSUE TITLE
Connect to moonraker to receive thumbnails

### ISSUE THREAD

**Issue by ramdaron** [OpenNeptune3D/display_connector#9]
To receive thumbnails from the moonraker, the `load_thumbnail_for_page` function makes a request to `http://localhost/`.
In most cases, this will work fine: the request from the script will come to the web server, after which it will be proxied to the moonraker.
But if only the mainsail is running on the host running display_connector, and the web interface (moonraker, for example) is running on another host, display_connector will not be able to connect to the moonraker and will not receive the thumbnails.

I suggest setting the `load_thumbnail_for_page` function to connect to `http://localhost:7125/` to request thumbnails directly from the moonraker.

**Comment by phillipthelen** [comment]
Yes that sounds good. Additionally I'll add a config option to change the entire url. Just in case someone uses a different port or something.
